name: Release to PyPI

on:
  push:
    tags: [ "v*" ]          # 只有推送 v 开头的 tag 才触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: python -m pip install --upgrade build twine
    - run: python -m build
    - name: publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
